<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '26a7803732d09e6447c637cce1befce0',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'SUMREC_ENDPOINT' => 'http://www.amiwx.net/dsrsumrec-vak-dev-v4a/dsrsumrec.php',
  'SUMREC_DBHOST' => '192.168.0.87',
  'DATABASE_URL' => 'pgsql://postgres:postgres@127.0.0.1:5487/routedb',
);
